### ISSUE TITLE
bug: Autoplay Not Working in Feed (aka discover) and Play Store

### ISSUE THREAD

**Issue by AdishSagarawat** [inotia00/revanced-patches#49]
### Type

Other

### Bug description

When I use Official Youtube it works flawlessly on RVX is sucks.

### Steps to reproduce

Uninstall Official YouTube and use RVX

### Relevant log output

```shell
I don't have any log.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
What does autoplay mean on the Play Store?

Add a description or attach a screenshot/screenrecord

**Comment by Delirious0700** [comment]
@inotia00, he probably means that after installing RVX, playing a youtube video directly in Google app feed, or any YouTube video in Play Store will throw a force close for the RVX patched youtube app.
I managed to get it working (that is playback worked in both apps) for 17.43.36 but can't remember how and not able to do it again. If you want a log, let me know.

**Comment by Antonbeard** [comment]
here is the error log:
java.lang.ExceptionInInitializerError
	at app.revanced.integrations.patches.LayoutSwitchOverridePatch.getLayoutSwitchOverride(LayoutSwitchOverridePatch.java:1)
	at ued.bV(PG:1)
	at ued.ce(PG:1)
	at wez.M(PG:5)
	at wez.a(PG:14)
	at aqim.a(PG:1)
	at led.a(PG:7)
	at ldj.run(PG:39)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at app.revanced.integrations.sponsorblock.StringRef.toString(StringRef.java:11)
	at app.revanced.integrations.sponsorblock.StringRef.str(StringRef.java:1)
	at app.revanced.integrations.settings.SettingsEnum.<clinit>(SettingsEnum.java:67)
	... 16 more
