### ISSUE TITLE
bug: Not building with manager and aborting

### ISSUE THREAD

**Issue by SpacEagle17** [inotia00/revanced-patches#76]
### Type

Error while patching

### Bug description

The patching gets aborted when using the manager version 0.0.43

### Steps to reproduce

Apply the recommended 50 patches and it aborts. Also tried with a few less, still aborting.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborting
Error:
java.lang.NoSuchMethodError: No static method softCompareTo(Lorg/jf/dexlib2/iface/Method;Lorg/jf/dexlib2/iface/reference/MethodReference;)Z in class Lapp/revanced/patcher/extensions/ExtensionsKt; or its super classes (declaration of 'app.revanced.patcher.extensions.ExtensionsKt' appears in base.apk)
	at app.revanced.extensions.MethodExtensions.findMutableMethodOf$revanced_patches(MethodExtensions.kt:37)
	at app.revanced.patches.youtube.ad.general.bytecode.patch.GeneralBytecodeAdsPatch.execute(GeneralBytecodeAdsPatch.kt:181)
	at app.revanced.patches.youtube.ad.general.bytecode.patch.GeneralBytecodeAdsPatch.execute(GeneralBytecodeAdsPatch.kt:38)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:336)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:356)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by mirairoses** [comment]
+1
